# Generated by Django 2.2.5 on 2019-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='availableproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField()),
                ('Product_No', models.IntegerField()),
                ('customer_id', models.CharField(max_length=50)),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Selling_Price', models.IntegerField()),
                ('Delivery_Date', models.DateField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Product_No', models.IntegerField()),
                ('Product_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Cost_Price', models.IntegerField()),
                ('Tot_Cost_Price', models.IntegerField()),
                ('Selling_Price', models.IntegerField()),
                ('Tot_selling_Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone_No', models.CharField(max_length=50)),
            ],
        ),
    ]
